services:
  component:
    container_name: app
    image: component
    build: .
    environment:
      - DEBUG_MODE=${DEBUG_MODE}
      - NO_EXCEPT=${NO_EXCEPT}
      - CPP_STD=${CPP_STD}
      - OPTIMIZATION_LEVEL=${OPTIMIZATION_LEVEL}
      - MODULE_NAME=${MODULE_NAME}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
